apiVersion: v1
kind: Service
metadata:
  name: {{ include "religious-community-hub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "religious-community-hub.name" . }}
    helm.sh/chart: {{ include "religious-community-hub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "religious-community-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
