apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: religious-community-hub
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: religious-community-hub
  minReplicas: 2
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: active_users
      target:
        type: AverageValue
        averageValue: 100
  - type: External
    external:
      metric:
        name: request_latency
      target:
        type: AverageValue
        averageValue: 200ms
