apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: religious-community-hub
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - religious-community-hub-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: religious-community-hub
        port:
          number: 3000
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx"
  - match:
    - uri:
        prefix: /static
    route:
    - destination:
        host: static-assets
        port:
          number: 8080
    retries:
      attempts: 2
      perTryTimeout: 1s
      retryOn: "connect-failure"

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: religious-community-hub
  namespace: default
spec:
  host: religious-community-hub
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 3
      interval: 1m
      baseEjectionTime: 3m
      maxEjectionPercent: 50

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: religious-community-hub-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
